// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/traceReader.proto

package com.expedia.open.tracing.api;

public interface SpanRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SpanRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string traceId = 1;</code>
   */
  java.lang.String getTraceId();
  /**
   * <code>string traceId = 1;</code>
   */
  com.google.protobuf.ByteString
      getTraceIdBytes();

  /**
   * <code>string spanId = 2;</code>
   */
  java.lang.String getSpanId();
  /**
   * <code>string spanId = 2;</code>
   */
  com.google.protobuf.ByteString
      getSpanIdBytes();
}
