// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/traceReader.proto

package com.expedia.open.tracing.api;

public final class TraceReaderOuterClass {
  private TraceReaderOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Trace_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Trace_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TraceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TraceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SpanRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SpanRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TracesSearchRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TracesSearchRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TracesSearchResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TracesSearchResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Field_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Field_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FieldValuesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FieldValuesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FieldNames_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FieldNames_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FieldValues_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FieldValues_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025api/traceReader.proto\032\nspan.proto\"3\n\005T" +
      "race\022\017\n\007traceId\030\001 \001(\t\022\031\n\nchildSpans\030\002 \003(" +
      "\0132\005.Span\"\037\n\014TraceRequest\022\017\n\007traceId\030\001 \001(" +
      "\t\".\n\013SpanRequest\022\017\n\007traceId\030\001 \001(\t\022\016\n\006spa" +
      "nId\030\002 \001(\t\"`\n\023TracesSearchRequest\022\026\n\006fiel" +
      "ds\030\001 \003(\0132\006.Field\022\021\n\tstartTime\030\002 \001(\003\022\017\n\007e" +
      "ndTime\030\003 \001(\003\022\r\n\005limit\030\004 \001(\005\",\n\022TracesSea" +
      "rchResult\022\026\n\006traces\030\001 \003(\0132\006.Trace\"$\n\005Fie" +
      "ld\022\014\n\004name\030\001 \001(\t\022\r\n\005value\030\002 \001(\t\"\007\n\005Empty" +
      "\"@\n\022FieldValuesRequest\022\021\n\tfieldName\030\001 \001(",
      "\t\022\027\n\007filters\030\002 \003(\0132\006.Field\"\033\n\nFieldNames" +
      "\022\r\n\005names\030\001 \003(\t\"\035\n\013FieldValues\022\016\n\006values" +
      "\030\001 \003(\t2\217\002\n\013TraceReader\0229\n\014searchTraces\022\024" +
      ".TracesSearchRequest\032\023.TracesSearchResul" +
      "t\022!\n\010getTrace\022\r.TraceRequest\032\006.Trace\022$\n\013" +
      "getRawTrace\022\r.TraceRequest\032\006.Trace\022!\n\nge" +
      "tRawSpan\022\014.SpanRequest\032\005.Span\022$\n\rgetFiel" +
      "dNames\022\006.Empty\032\013.FieldNames\0223\n\016getFieldV" +
      "alues\022\023.FieldValuesRequest\032\014.FieldValues" +
      "B \n\034com.expedia.open.tracing.apiP\001b\006prot",
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.expedia.open.tracing.SpanOuterClass.getDescriptor(),
        }, assigner);
    internal_static_Trace_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Trace_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Trace_descriptor,
        new java.lang.String[] { "TraceId", "ChildSpans", });
    internal_static_TraceRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_TraceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TraceRequest_descriptor,
        new java.lang.String[] { "TraceId", });
    internal_static_SpanRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_SpanRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SpanRequest_descriptor,
        new java.lang.String[] { "TraceId", "SpanId", });
    internal_static_TracesSearchRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_TracesSearchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TracesSearchRequest_descriptor,
        new java.lang.String[] { "Fields", "StartTime", "EndTime", "Limit", });
    internal_static_TracesSearchResult_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_TracesSearchResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TracesSearchResult_descriptor,
        new java.lang.String[] { "Traces", });
    internal_static_Field_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_Field_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Field_descriptor,
        new java.lang.String[] { "Name", "Value", });
    internal_static_Empty_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_FieldValuesRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_FieldValuesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FieldValuesRequest_descriptor,
        new java.lang.String[] { "FieldName", "Filters", });
    internal_static_FieldNames_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_FieldNames_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FieldNames_descriptor,
        new java.lang.String[] { "Names", });
    internal_static_FieldValues_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_FieldValues_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FieldValues_descriptor,
        new java.lang.String[] { "Values", });
    com.expedia.open.tracing.SpanOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
